insert into Course (id, title) values (1, 'Internal Auditor');
insert into Course (id, title) values (2, 'Payment Adjustment Coordinator');
insert into Course (id, title) values (3, 'Geological Engineer');
insert into Course (id, title) values (4, 'Chemical Engineer');
insert into Course (id, title) values (5, 'Information Systems Manager');
insert into Course (id, title) values (6, 'Nurse');
insert into Course (id, title) values (7, 'Technical Writer');
insert into Course (id, title) values (8, 'Design Engineer');
insert into Course (id, title) values (9, 'Technical Writer');
insert into Course (id, title) values (10, 'Chief Design Engineer');
insert into Course (id, title) values (11, 'Quality Control Specialist');
insert into Course (id, title) values (12, 'Accountant II');
insert into Course (id, title) values (13, 'Programmer I');
insert into Course (id, title) values (14, 'Geological Engineer');
insert into Course (id, title) values (15, 'Biostatistician II');
insert into Course (id, title) values (16, 'Occupational Therapist');
insert into Course (id, title) values (17, 'Compensation Analyst');
insert into Course (id, title) values (18, 'Internal Auditor');
insert into Course (id, title) values (19, 'Dental Hygienist');
insert into Course (id, title) values (20, 'Senior Cost Accountant');
insert into Course (id, title) values (21, 'Junior Executive');
insert into Course (id, title) values (22, 'Structural Engineer');
insert into Course (id, title) values (23, 'Database Administrator I');
insert into Course (id, title) values (24, 'VP Marketing');
insert into Course (id, title) values (25, 'Developer I');
insert into Course (id, title) values (26, 'Health Coach III');
insert into Course (id, title) values (27, 'Community Outreach Specialist');
insert into Course (id, title) values (28, 'Human Resources Manager');
insert into Course (id, title) values (29, 'Financial Advisor');
insert into Course (id, title) values (30, 'Project Manager');
insert into Course (id, title) values (31, 'Help Desk Technician');
insert into Course (id, title) values (32, 'Financial Analyst');
insert into Course (id, title) values (33, 'Design Engineer');
insert into Course (id, title) values (34, 'Developer III');
insert into Course (id, title) values (35, 'Electrical Engineer');
insert into Course (id, title) values (36, 'Engineer II');
insert into Course (id, title) values (37, 'Marketing Manager');
insert into Course (id, title) values (38, 'Compensation Analyst');
insert into Course (id, title) values (39, 'Programmer IV');
insert into Course (id, title) values (40, 'Programmer III');
insert into Course (id, title) values (41, 'Information Systems Manager');
insert into Course (id, title) values (42, 'VP Accounting');
insert into Course (id, title) values (43, 'Senior Editor');
insert into Course (id, title) values (44, 'Administrative Officer');
insert into Course (id, title) values (45, 'Design Engineer');
insert into Course (id, title) values (46, 'Administrative Assistant II');
insert into Course (id, title) values (47, 'Web Designer II');
insert into Course (id, title) values (48, 'Cost Accountant');
insert into Course (id, title) values (49, 'Occupational Therapist');
insert into Course (id, title) values (50, 'Account Coordinator');
insert into Course (id, title) values (51, 'Software Test Engineer IV');
insert into Course (id, title) values (52, 'Research Nurse');
insert into Course (id, title) values (53, 'Nuclear Power Engineer');
insert into Course (id, title) values (54, 'Structural Analysis Engineer');
insert into Course (id, title) values (55, 'Editor');
insert into Course (id, title) values (56, 'Social Worker');
insert into Course (id, title) values (57, 'Developer III');
insert into Course (id, title) values (58, 'Staff Scientist');
insert into Course (id, title) values (59, 'Sales Representative');
insert into Course (id, title) values (60, 'Senior Developer');
insert into Course (id, title) values (61, 'Geologist II');
insert into Course (id, title) values (62, 'VP Marketing');
insert into Course (id, title) values (63, 'Speech Pathologist');
insert into Course (id, title) values (64, 'Project Manager');
insert into Course (id, title) values (65, 'Project Manager');
insert into Course (id, title) values (66, 'Internal Auditor');
insert into Course (id, title) values (67, 'Marketing Manager');
insert into Course (id, title) values (68, 'Human Resources Manager');
insert into Course (id, title) values (69, 'Human Resources Assistant I');
insert into Course (id, title) values (70, 'Accountant II');
insert into Course (id, title) values (71, 'Graphic Designer');
insert into Course (id, title) values (72, 'Developer III');
insert into Course (id, title) values (73, 'Help Desk Technician');
insert into Course (id, title) values (74, 'Structural Engineer');
insert into Course (id, title) values (75, 'Account Representative IV');
insert into Course (id, title) values (76, 'Physical Therapy Assistant');
insert into Course (id, title) values (77, 'Occupational Therapist');
insert into Course (id, title) values (78, 'Editor');
insert into Course (id, title) values (79, 'Biostatistician III');
insert into Course (id, title) values (80, 'Structural Analysis Engineer');
insert into Course (id, title) values (81, 'Safety Technician I');
insert into Course (id, title) values (82, 'Research Assistant II');
insert into Course (id, title) values (83, 'Software Test Engineer I');
insert into Course (id, title) values (84, 'Automation Specialist I');
insert into Course (id, title) values (85, 'Compensation Analyst');
insert into Course (id, title) values (86, 'Geological Engineer');
insert into Course (id, title) values (87, 'Developer III');
insert into Course (id, title) values (88, 'Computer Systems Analyst I');
insert into Course (id, title) values (89, 'Staff Accountant I');
insert into Course (id, title) values (90, 'Payment Adjustment Coordinator');
insert into Course (id, title) values (91, 'Electrical Engineer');
insert into Course (id, title) values (92, 'Software Engineer IV');
insert into Course (id, title) values (93, 'Social Worker');
insert into Course (id, title) values (94, 'Statistician IV');
insert into Course (id, title) values (95, 'Systems Administrator I');
insert into Course (id, title) values (96, 'Professor');
insert into Course (id, title) values (97, 'Staff Accountant I');
insert into Course (id, title) values (98, 'Health Coach III');
insert into Course (id, title) values (99, 'Senior Editor');
insert into Course (id, title) values (100, 'Teacher');