/* Insert students */
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Lodwick', 'Robin', '2002-05-12', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Arlidge', 'Gustav', '2002-02-03', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Reisin', 'Celinka', '2000-08-05', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Walworth', 'Zachary', '1996-06-19', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Maffin', 'Barbee', '2000-05-17', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Celli', 'Diena', '2002-02-21', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Crawforth', 'Eliza', '2000-12-23', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Holworth', 'Noel', '2002-07-05', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Birley', 'Lindy', '1997-01-25', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Orlton', 'Wynny', '2001-07-03', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Warburton', 'Kelby', '2002-06-03', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Sallarie', 'Mordy', '2001-07-13', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Corkett', 'Lacie', '2002-10-21', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Cardello', 'Margret', '2000-01-16', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Dresser', 'Worden', '1999-12-08', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Sleeny', 'Tull', '1997-02-09', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Bothe', 'Goldina', '2001-06-05', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Dumphy', 'Benny', '2002-11-06', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Twede', 'Haven', '2001-08-27', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Dutt', 'Shirley', '2002-04-25', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Nichols', 'Rudolfo', '1999-03-21', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Paul', 'Ian', '2001-03-06', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Mylchreest', 'Zia', '1999-11-27', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Bloor', 'Ellary', '1997-09-22', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Filippello', 'Magdaia', '2000-03-03', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('McCrum', 'Thain', '2001-07-12', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Karolyi', 'Catrina', '1997-05-22', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Lotterington', 'Atlante', '2001-05-17', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('MacGuigan', 'Donaugh', '1999-07-09', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('McDavitt', 'Juliana', '1996-11-23', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Couchman', 'Esdras', '1995-12-30', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Purvis', 'Georgeta', '2000-03-27', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Pillifant', 'Vivienne', '1996-05-11', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Jolland', 'Othelia', '2000-01-01', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Mardlin', 'Cristabel', '2002-07-23', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Stolting', 'Shelby', '1998-03-10', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Rothert', 'Shanan', '2001-07-25', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('McShea', 'Lindsay', '1996-01-27', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Boniface', 'Fifine', '1997-08-19', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Petrescu', 'Lloyd', '2002-07-11', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Passie', 'Germain', '2001-04-23', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Mathet', 'Vic', '1997-05-20', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Whatman', 'Jolie', '2000-06-06', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Sickling', 'Amanda', '2001-07-18', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Adamovitch', 'Kirby', '2002-10-29', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Getch', 'Nollie', '2001-04-19', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Minet', 'Felicia', '2000-02-15', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Hartigan', 'Ari', '1998-10-04', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Benoy', 'Buddie', '1997-07-16', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Taudevin', 'Adriana', '1998-09-23', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('MacCumiskey', 'Vernon', '1997-09-05', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Rosensaft', 'Lark', '1998-09-06', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Storch', 'Lucila', '2000-11-15', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('MacCarrane', 'Anderea', '1996-11-28', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Alabaster', 'Letty', '2001-03-29', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Orrobin', 'Noll', '2000-07-07', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Casone', 'Basile', '2001-02-17', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Waker', 'Alvin', '1998-09-12', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Hooks', 'Matty', '2001-10-12', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Ruggier', 'Ferrel', '2000-04-19', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Emby', 'Marget', '1996-11-06', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Treske', 'Jack', '1996-04-13', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Carden', 'Elli', '1999-03-29', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Marcone', 'Ban', '1995-12-22', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Bangiard', 'Gardie', '2001-01-16', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Lindblad', 'Meredith', '1999-10-06', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Moyne', 'Junie', '2001-12-08', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Teale', 'Debby', '2002-01-02', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Klees', 'Osborn', '1999-03-11', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Benbrick', 'Renard', '1996-10-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Dadge', 'Peggie', '2002-02-20', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Mercer', 'Dore', '1998-08-29', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Itzkov', 'Betsey', '1997-09-26', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('O''Henehan', 'Dedra', '1998-11-01', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('O''Fallon', 'Maurice', '1997-05-17', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Eadington', 'Hally', '1998-12-28', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Cosham', 'Chryste', '1999-06-02', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Moyes', 'Abran', '2002-06-07', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Bonnet', 'Ardine', '1997-08-11', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Yelding', 'Mano', '1996-06-29', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Jantet', 'Jaye', '1998-09-09', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Duplain', 'Adrienne', '1996-08-01', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Dudin', 'Bartholomeus', '1996-12-02', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Overlow', 'Kerry', '1998-11-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Kitchin', 'Darbie', '1996-05-25', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Corney', 'Willie', '2001-01-08', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Passo', 'Giorgia', '2002-05-30', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Biskupski', 'Marvin', '1999-03-30', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Jaksic', 'Orel', '1996-09-12', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Godley', 'Jacqui', '1996-09-14', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Luis', 'Gaby', '1999-08-26', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Arman', 'Luci', '2000-01-03', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Bachanski', 'Waldo', '1999-03-05', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Bithany', 'Fredia', '1997-06-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Struthers', 'Chelsey', '1997-12-13', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Waud', 'Alma', '1998-11-17', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Valero', 'Gifford', '1996-02-19', false);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Hicks', 'Berta', '1996-06-21', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Turnock', 'Gilbertina', '2000-11-04', true);
insert into Student (lastname, firstname, birthdate, wantsnewletter) values ('Angear', 'Vassili', '1996-03-20', false);


/* insert course */
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Goldenrod');
insert into Course (title) values ('Green');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Green');
insert into Course (title) values ('Goldenrod');
insert into Course (title) values ('Khaki');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Aquamarine');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Maroon');
insert into Course (title) values ('Fuscia');
insert into Course (title) values ('Maroon');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Pink');
insert into Course (title) values ('Mauv');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Blue');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Maroon');
insert into Course (title) values ('Turquoise');
insert into Course (title) values ('Pink');
insert into Course (title) values ('Goldenrod');
insert into Course (title) values ('Pink');
insert into Course (title) values ('Mauv');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Blue');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Pink');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Fuscia');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Yellow');
insert into Course (title) values ('Fuscia');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Goldenrod');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Teal');
insert into Course (title) values ('Khaki');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Pink');
insert into Course (title) values ('Aquamarine');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Green');
insert into Course (title) values ('Aquamarine');
insert into Course (title) values ('Teal');
insert into Course (title) values ('Aquamarine');
insert into Course (title) values ('Aquamarine');
insert into Course (title) values ('Aquamarine');
insert into Course (title) values ('Green');
insert into Course (title) values ('Pink');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Khaki');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Turquoise');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Goldenrod');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Yellow');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Goldenrod');
insert into Course (title) values ('Maroon');
insert into Course (title) values ('Aquamarine');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Maroon');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Red');
insert into Course (title) values ('Turquoise');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Maroon');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Indigo');
insert into Course (title) values ('Violet');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Green');
insert into Course (title) values ('Maroon');
insert into Course (title) values ('Red');
insert into Course (title) values ('Yellow');
insert into Course (title) values ('Blue');
insert into Course (title) values ('Red');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Red');
insert into Course (title) values ('Puce');
insert into Course (title) values ('Yellow');
insert into Course (title) values ('Turquoise');
insert into Course (title) values ('Purple');
insert into Course (title) values ('Orange');
insert into Course (title) values ('Crimson');
insert into Course (title) values ('Green');
insert into Course (title) values ('Blue');
insert into Course (title) values ('Yellow');
insert into Course (title) values ('Yellow');
insert into Course (title) values ('Fuscia');
insert into Course (title) values ('Goldenrod');


/* insert into course material*/
insert into Coursematerial (course_id, url) values (1, 'Maroon');
insert into Coursematerial (course_id, url) values (2, 'Blue');
insert into Coursematerial (course_id, url) values (3, 'Indigo');
insert into Coursematerial (course_id, url) values (4, 'Khaki');
insert into Coursematerial (course_id, url) values (5, 'Purple');
insert into Coursematerial (course_id, url) values (6, 'Puce');
insert into Coursematerial (course_id, url) values (7, 'Pink');
insert into Coursematerial (course_id, url) values (8, 'Fuscia');
insert into Coursematerial (course_id, url) values (9, 'Khaki');
insert into Coursematerial (course_id, url) values (10, 'Turquoise');
insert into Coursematerial (course_id, url) values (11, 'Green');
insert into Coursematerial (course_id, url) values (12, 'Aquamarine');
insert into Coursematerial (course_id, url) values (13, 'Yellow');
insert into Coursematerial (course_id, url) values (14, 'Orange');
insert into Coursematerial (course_id, url) values (15, 'Blue');
insert into Coursematerial (course_id, url) values (16, 'Puce');
insert into Coursematerial (course_id, url) values (17, 'Puce');
insert into Coursematerial (course_id, url) values (18, 'Khaki');
insert into Coursematerial (course_id, url) values (19, 'Orange');
insert into Coursematerial (course_id, url) values (20, 'Fuscia');
insert into Coursematerial (course_id, url) values (21, 'Fuscia');
insert into Coursematerial (course_id, url) values (22, 'Orange');
insert into Coursematerial (course_id, url) values (23, 'Turquoise');
insert into Coursematerial (course_id, url) values (24, 'Green');
insert into Coursematerial (course_id, url) values (25, 'Indigo');
insert into Coursematerial (course_id, url) values (26, 'Purple');
insert into Coursematerial (course_id, url) values (27, 'Fuscia');
insert into Coursematerial (course_id, url) values (28, 'Goldenrod');
insert into Coursematerial (course_id, url) values (29, 'Khaki');
insert into Coursematerial (course_id, url) values (30, 'Green');
insert into Coursematerial (course_id, url) values (31, 'Indigo');
insert into Coursematerial (course_id, url) values (32, 'Violet');
insert into Coursematerial (course_id, url) values (33, 'Green');
insert into Coursematerial (course_id, url) values (34, 'Khaki');
insert into Coursematerial (course_id, url) values (35, 'Mauv');
insert into Coursematerial (course_id, url) values (36, 'Orange');
insert into Coursematerial (course_id, url) values (37, 'Crimson');
insert into Coursematerial (course_id, url) values (38, 'Khaki');
insert into Coursematerial (course_id, url) values (39, 'Turquoise');
insert into Coursematerial (course_id, url) values (40, 'Violet');
insert into Coursematerial (course_id, url) values (41, 'Pink');
insert into Coursematerial (course_id, url) values (42, 'Blue');
insert into Coursematerial (course_id, url) values (43, 'Violet');
insert into Coursematerial (course_id, url) values (44, 'Red');
insert into Coursematerial (course_id, url) values (45, 'Teal');
insert into Coursematerial (course_id, url) values (46, 'Pink');
insert into Coursematerial (course_id, url) values (47, 'Orange');
insert into Coursematerial (course_id, url) values (48, 'Purple');
insert into Coursematerial (course_id, url) values (49, 'Indigo');
insert into Coursematerial (course_id, url) values (50, 'Crimson');
insert into Coursematerial (course_id, url) values (51, 'Khaki');
insert into Coursematerial (course_id, url) values (52, 'Puce');
insert into Coursematerial (course_id, url) values (53, 'Violet');
insert into Coursematerial (course_id, url) values (54, 'Green');
insert into Coursematerial (course_id, url) values (55, 'Crimson');
insert into Coursematerial (course_id, url) values (56, 'Crimson');
insert into Coursematerial (course_id, url) values (57, 'Fuscia');
insert into Coursematerial (course_id, url) values (58, 'Indigo');
insert into Coursematerial (course_id, url) values (59, 'Purple');
insert into Coursematerial (course_id, url) values (60, 'Purple');
insert into Coursematerial (course_id, url) values (61, 'Puce');
insert into Coursematerial (course_id, url) values (62, 'Mauv');
insert into Coursematerial (course_id, url) values (63, 'Aquamarine');
insert into Coursematerial (course_id, url) values (64, 'Teal');
insert into Coursematerial (course_id, url) values (65, 'Khaki');
insert into Coursematerial (course_id, url) values (66, 'Turquoise');
insert into Coursematerial (course_id, url) values (67, 'Violet');
insert into Coursematerial (course_id, url) values (68, 'Puce');
insert into Coursematerial (course_id, url) values (69, 'Yellow');
insert into Coursematerial (course_id, url) values (70, 'Puce');
insert into Coursematerial (course_id, url) values (71, 'Indigo');
insert into Coursematerial (course_id, url) values (72, 'Puce');
insert into Coursematerial (course_id, url) values (73, 'Indigo');
insert into Coursematerial (course_id, url) values (74, 'Goldenrod');
insert into Coursematerial (course_id, url) values (75, 'Violet');
insert into Coursematerial (course_id, url) values (76, 'Violet');
insert into Coursematerial (course_id, url) values (77, 'Yellow');
insert into Coursematerial (course_id, url) values (78, 'Fuscia');
insert into Coursematerial (course_id, url) values (79, 'Khaki');
insert into Coursematerial (course_id, url) values (80, 'Crimson');
insert into Coursematerial (course_id, url) values (81, 'Teal');
insert into Coursematerial (course_id, url) values (82, 'Puce');
insert into Coursematerial (course_id, url) values (83, 'Green');
insert into Coursematerial (course_id, url) values (84, 'Pink');
insert into Coursematerial (course_id, url) values (85, 'Blue');
insert into Coursematerial (course_id, url) values (86, 'Khaki');
insert into Coursematerial (course_id, url) values (87, 'Goldenrod');
insert into Coursematerial (course_id, url) values (88, 'Violet');
insert into Coursematerial (course_id, url) values (89, 'Violet');
insert into Coursematerial (course_id, url) values (90, 'Crimson');
insert into Coursematerial (course_id, url) values (91, 'Crimson');
insert into Coursematerial (course_id, url) values (92, 'Indigo');
insert into Coursematerial (course_id, url) values (93, 'Aquamarine');
insert into Coursematerial (course_id, url) values (94, 'Mauv');
insert into Coursematerial (course_id, url) values (95, 'Puce');
insert into Coursematerial (course_id, url) values (96, 'Green');
insert into Coursematerial (course_id, url) values (97, 'Teal');
insert into Coursematerial (course_id, url) values (98, 'Orange');
insert into Coursematerial (course_id, url) values (99, 'Yellow');
insert into Coursematerial (course_id, url) values (100, 'Goldenrod');